name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.4.7'
          - '3.3.10'
          - jruby-9.4.14.0
        solr_version: ['']
        include:
          - ruby: '3.4.7'
            solr_version: '8.11.4'
          - ruby: '3.4.7'
            solr_version: '9.6.1'
    env:
      SOLR_WRAPPER_SOLR_VERSION: ${{ matrix.solr_version }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
      env:
        ENGINE_CART_RAILS_OPTIONS: '--skip-git --skip-listen --skip-spring --skip-keeps --skip-action-cable --skip-coffee --skip-test'
